apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curlchecker
  namespace: linkfn
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: linkcheck
            image:  makerbot/linkfn:checker-method
          restartPolicy: Never